In [ ]:
#OneHotEncoding

In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv(r'C:\Users\Naveen s kamatagi\Downloads\4-hour-course-xl-files\IndividualDetails11.csv',encoding='latin1')

In [3]:
dataset.head(4)

,id,government_id,diagnosed_date,age,gender,detected_city,detected_district,detected_state,nationality,current_status,status_change_date,notes
0,0,KL-TS-P1,30-01-2020,20,F,Thrissur,Thrissur,Kerala,India,Recovered,14-02-2020,Travelled from Wuhan
1,1,KL-AL-P1,02-02-2020,NaN,NaN,Alappuzha,Alappuzha,Kerala,India,Recovered,14-02-2020,Travelled from Wuhan
2,2,KL-KS-P1,03-02-2020,NaN,NaN,Kasaragod,Kasaragod,Kerala,India,Recovered,14-02-2020,Travelled from Wuhan
3,3,DL-P1,02-03-2020,45,M,East Delhi (Mayur Vihar),East Delhi,Delhi,India,Recovered,15-03-2020,"Travelled from Austria, Italy"

In [4]:
en_data=dataset[["gender"]]

In [5]:
pd.get_dummies(en_data)

       gender_F  gender_M
0          True     False
1         False     False
2         False     False
3         False      True
4         False      True
...         ...       ...
28177     False     False
28178     False     False
28179     False     False
28180     False     False
28181     False     False

[28182 rows x 2 columns]

In [6]:
from sklearn.preprocessing import OneHotEncoder

In [7]:
ohe=OneHotEncoder()

In [8]:
ohe.fit_transform(en_data)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 28182 stored elements and shape (28182, 3)>

In [9]:
ohe.fit_transform(en_data).toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]], shape=(28182, 3))

In [10]:
ar=ohe.fit_transform(en_data).toarray()

In [11]:
pd.DataFrame(ar,columns=["gender_F","gender_M","gender_o"])

       gender_F  gender_M  gender_o
0           1.0       0.0       0.0
1           0.0       0.0       1.0
2           0.0       0.0       1.0
3           0.0       1.0       0.0
4           0.0       1.0       0.0
...         ...       ...       ...
28177       0.0       0.0       1.0
28178       0.0       0.0       1.0
28179       0.0       0.0       1.0
28180       0.0       0.0       1.0
28181       0.0       0.0       1.0

[28182 rows x 3 columns]

In [12]:
#label Encoding

In [15]:
df=pd.DataFrame({"names":["cat","dog","pig","blck","zibra"]})

In [13]:
from sklearn.preprocessing import LabelEncoder

In [18]:
le=LabelEncoder()
df["en_data"]=le.fit_transform(df["names"])

In [19]:
 df

   names  en_data
0    cat        1
1    dog        2
2    pig        3
3   blck        0
4  zibra        4

In [27]:
dataset["detected_city"].unique()

array([471,  11, 212, 122, 169, 178, 151,   4, 511, 185, 141, 488, 256,
       201, 415, 479, 184,  50, 206, 392,  14, 245, 226,  93, 104, 301,
       384, 313, 344, 264, 197, 111, 493, 341, 468,   7, 463, 199, 367,
       336, 508, 305,  30, 110, 409, 198, 276,  63, 424, 209, 260, 275,
       348, 234,  51, 138,  95, 445, 224, 189, 116,  83, 485, 227, 351,
       404, 258,  39, 126, 407, 456, 502, 412,  25, 139,  48, 294, 105,
       177, 350,   6, 490,  56, 127, 365, 203, 176, 210, 506, 153, 147,
       362, 429, 132, 299, 380, 337, 136, 308, 448, 121,  59, 257, 405,
       499, 148, 492, 164, 303, 302, 106, 304, 372,  60, 242, 247,  52,
       498, 193, 230,   1, 474, 503, 442, 462, 495, 359,  36, 422, 447,
       128, 207, 383, 476, 273, 186, 217, 428, 223, 171, 394, 284,  98,
       388, 395, 220, 231,  82,  47, 334, 381, 450, 423, 285, 172, 484,
       190, 483, 265, 120, 408, 505, 142, 339,  68,  55, 349,  35, 397,
       119, 437,  21,  40, 480, 391, 358, 109, 360,  18, 289, 249, 216,
         9, 137, 451, 156, 353, 406, 507,  53, 254, 268, 102,  13, 324,
       287, 461, 347, 332, 196,  73, 165, 425, 478, 261, 208, 150, 251,
       202, 159, 446, 465, 292, 309,  22,  19, 385, 291, 389, 290, 211,
        69, 101, 487, 379, 510,  46, 467, 113, 170, 396, 154, 411,  67,
       259, 439, 144,  43, 225, 470,  49, 469,   5,  71,  54, 369, 262,
       180, 317, 228, 390, 269, 155, 161, 455, 335, 252,  38, 103, 427,
       330, 221, 311, 281, 152,   3, 192, 129, 229, 133,  28, 352, 449,
       321, 174, 472, 346, 100, 219, 416, 343, 274,  42,   8,  57,  72,
       112,  76,  32,  81, 310, 357,  44, 145, 417,  77,   2, 318, 135,
       319, 440, 368, 398, 328,  15, 131, 194, 331, 130,  10, 213, 363,
       322, 320,  29, 240, 149, 491, 315, 376, 125, 373, 235, 238, 418,
       108, 333, 482, 477, 453, 300, 188, 187,  89,  31,  86, 236, 496,
        74, 475, 279, 157, 457, 481, 312, 175,  23, 200,  17, 460, 158,
       443, 140, 179,  12,  45, 278, 215, 387, 329, 143,  20, 241, 296,
       436, 246, 452, 426, 250, 107,  27, 288, 272, 244, 327, 195, 297,
       123,  24,  37, 114, 271, 233, 400, 163, 366, 298, 454, 386, 237,
       466, 239, 374,  78, 489,  58, 314, 117, 504, 414, 459, 167, 277,
        64, 399, 118, 270, 345,  88,  84, 458, 413, 375, 326, 402, 444,
        16, 134,  75, 162, 316,  62,  97, 323,  34,  99, 267, 214,  70,
       486, 166,  33, 160, 403, 438, 168, 181, 222,   0, 191, 266, 354,
       355, 393, 464, 494,  66, 509,  41, 173, 497, 253, 377, 441,  65,
       410,  91, 371, 378,  80, 306, 307,  85, 243, 218, 205, 255, 501,
        92, 293,  96, 248, 232, 370, 295, 204,  94, 342, 283, 124, 286,
       361, 431,  79, 146, 182, 401, 183,  26, 338, 115, 473,  90, 280,
       340, 420, 282, 430, 432,  87, 325, 434, 419, 364, 356, 421, 382,
        61, 500, 433, 435, 263])

In [22]:
la=LabelEncoder()
la.fit(dataset["detected_city"])

LabelEncoder()

In [23]:
la.transform(dataset["detected_city"])

array([471,  11, 212, ..., 511, 511, 511], shape=(28182,))

In [26]:
dataset["detected_city"]=la.transform(dataset["detected_city"])

In [28]:
#Ordinary Encoding

In [30]:
dn=pd.DataFrame({"size":["s","m","l","xl","s","m","l","xl","s","m"]})

In [31]:
dn

  size
0    s
1    m
2    l
3   xl
4    s
5    m
6    l
7   xl
8    s
9    m

In [32]:
ord_data=[["s","m","l","xl"]]

In [33]:
from sklearn.preprocessing import OrdinalEncoder

In [34]:
oe=OrdinalEncoder()
oe.fit(dn[["size"]])

OrdinalEncoder()

In [35]:
oe.transform(dn[["size"]])

array([[2.],
       [1.],
       [0.],
       [3.],
       [2.],
       [1.],
       [0.],
       [3.],
       [2.],
       [1.]])

In [36]:
dn["size_en"]=oe.transform(dn[["size"]])

In [37]:
dn

  size  size_en
0    s      2.0
1    m      1.0
2    l      0.0
3   xl      3.0
4    s      2.0
5    m      1.0
6    l      0.0
7   xl      3.0
8    s      2.0
9    m      1.0

In [38]:
#Map Function

In [39]:
ord_data1={"s":0,"m":2,"l":5,"xl":3}

In [40]:
dn["size"].map(ord_data1)

0    0
1    2
2    5
3    3
4    0
5    2
6    5
7    3
8    0
9    2
Name: size, dtype: int64

In [41]:
dn["size_en_map"]=dn["size"].map(ord_data1)

In [42]:
dn

  size  size_en  size_en_map
0    s      2.0            0
1    m      1.0            2
2    l      0.0            5
3   xl      3.0            3
4    s      2.0            0
5    m      1.0            2
6    l      0.0            5
7   xl      3.0            3
8    s      2.0            0
9    m      1.0            2

In [43]:
#using real data perform the ordinal Encoding

In [46]:
dataset["current_status"].unique()

array(['Recovered', 'Hospitalized', 'Deceased', 'Migrated'], dtype=object)

In [47]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28182 entries, 0 to 28181
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  28182 non-null  int64
 1   government_id       2997 non-null   object
 2   diagnosed_date      28182 non-null  object
 3   age                 2346 non-null   object
 4   gender              5313 non-null   object
 5   detected_city       28182 non-null  int64
 6   detected_district   21198 non-null  object
 7   detected_state      28182 non-null  object
 8   nationality         2709 non-null   object
 9   current_status      28182 non-null  object
 10  status_change_date  27780 non-null  object
 11  notes               26847 non-null  object
dtypes: int64(2), object(10)
memory usage: 2.6+ MB

In [48]:
en_data_ordinal=[["Recovered","Hospitalized","Deceased","Migrated"]]

In [50]:
one=OrdinalEncoder(categories=en_data_ordinal)

In [52]:
dataset["current_status"]=one.fit_transform(dataset[["current_status"]])

In [53]:
dataset

,id,government_id,diagnosed_date,age,gender,detected_city,detected_district,detected_state,nationality,current_status,status_change_date,notes
0,0,KL-TS-P1,30-01-2020,20,F,471,Thrissur,Kerala,India,0.0,14-02-2020,Travelled from Wuhan
1,1,KL-AL-P1,02-02-2020,NaN,NaN,11,Alappuzha,Kerala,India,0.0,14-02-2020,Travelled from Wuhan
2,2,KL-KS-P1,03-02-2020,NaN,NaN,212,Kasaragod,Kerala,India,0.0,14-02-2020,Travelled from Wuhan
3,3,DL-P1,02-03-2020,45,M,122,East Delhi,Delhi,India,0.0,15-03-2020,"Travelled from Austria, Italy"
4,4,TS-P1,02-03-2020,24,M,169,Hyderabad,Telangana,India,0.0,02-03-2020,"Travelled from Dubai to Bangalore on 20th Feb,..."
...,...,...,...,...,...,...,...,...,...,...,...,...
28177,28178,NaN,22-04-2020,NaN,NaN,511,NaN,Maharashtra,NaN,1.0,NaN,Correction for district count
28178,28179,NaN,24-04-2020,NaN,NaN,511,Nagpur,Maharashtra,NaN,1.0,NaN,Correction for district count
28179,28180,NaN,24-04-2020,NaN,NaN,511,NaN,Maharashtra,NaN,1.0,NaN,Correction for district count
28180,28181,NaN,25-04-2020,NaN,NaN,511,Nagpur,Maharashtra,NaN,1.0,NaN,Correction for district count
28181,28182,NaN,25-04-2020,NaN,NaN,511,NaN,Maharashtra,NaN,1.0,NaN,Correction for district count

In [54]:
dataset.head(5)

,id,government_id,diagnosed_date,age,gender,detected_city,detected_district,detected_state,nationality,current_status,status_change_date,notes
0,0,KL-TS-P1,30-01-2020,20,F,471,Thrissur,Kerala,India,0.0,14-02-2020,Travelled from Wuhan
1,1,KL-AL-P1,02-02-2020,NaN,NaN,11,Alappuzha,Kerala,India,0.0,14-02-2020,Travelled from Wuhan
2,2,KL-KS-P1,03-02-2020,NaN,NaN,212,Kasaragod,Kerala,India,0.0,14-02-2020,Travelled from Wuhan
3,3,DL-P1,02-03-2020,45,M,122,East Delhi,Delhi,India,0.0,15-03-2020,"Travelled from Austria, Italy"
4,4,TS-P1,02-03-2020,24,M,169,Hyderabad,Telangana,India,0.0,02-03-2020,"Travelled from Dubai to Bangalore on 20th Feb,..."